"""Add cancel columns for order cancelation featue

Revision ID: 16a2591e1e94
Revises: 72b6771ba62a
Create Date: 2025-12-16 12:22:35.469585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16a2591e1e94'
down_revision: Union[str, Sequence[str], None] = '72b6771ba62a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('cancel_reason', sa.Text(), nullable=True))
    op.execute("ALTER TYPE itemstatus ADD VALUE IF NOT EXISTS 'cancelled'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'cancel_reason')
    op.drop_column('orders', 'cancelled_at')
    # ### end Alembic commands ###
