"""Add notes and delivery address to the order and order item table

Revision ID: 72b6771ba62a
Revises: fe5ab77699d3
Create Date: 2025-12-06 21:46:18.374002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72b6771ba62a'
down_revision: Union[str, Sequence[str], None] = 'fe5ab77699d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('delivery_address', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'notes')
    op.drop_column('orders', 'delivery_address')
    op.drop_column('order_items', 'notes')
    # ### end Alembic commands ###
